"""Actual generated PCM and retained synthetic accounts; no live listener claimed."""

from copy import deepcopy
from datetime import datetime, timezone, timedelta
import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from server.main import app
from server.registry import storage
from server.generation_decisions import retain, POLICY
from server.generation_workflow import execute
from test_generation_workflow import library, payload  # noqa: F401


@pytest.fixture
def decision_case(library, request):  # noqa: F811
    store, source = library
    generation = payload(source)
    generation["execution"].update(
        provider="synthesis", model="additive", synthesis={"frequency": 330, "partials": [1, 0.3]}
    )
    output = execute(generation)
    assert output["linkage_status"] == "complete", output
    link = output["outputs"][0]
    generated = store.get(link["akousma_id"])
    later = json.loads((Path(__file__).parent / "fixtures/subsequent-listening.json").read_text())
    timestamp = (
        (datetime.now(timezone.utc) + timedelta(seconds=1))
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )
    later["created_at"] = timestamp
    later["provenance"]["created_at"] = timestamp
    later["audio"] = deepcopy(generated["audio"])
    later["auditum"]["listenings"][0]["created_at"] = timestamp
    later["auditum"]["listenings"][0]["note"] = (
        "Synthetic retained-account fixture bound to generated bytes; not a live human pass."
    )
    if getattr(request, "param", None) == "earlier":
        later["auditum"]["listenings"][0]["created_at"] = "2000-01-01T00:00:00Z"
    if getattr(request, "param", None) == "restricted":
        later["provenance"]["consent_status"] = "restricted"
    if getattr(request, "param", None) == "different_audio":
        from server.audio_io import write_sine_wav

        other = storage.settings.output_root / "different-later-audio.wav"
        write_sine_wav(
            other, duration=0.1, sample_rate=44100, frequency=550, amplitude=0.1, channels=1
        )
        later["audio"]["uri"] = other.as_uri()
    store.put(later)
    # Emulate the trusted bridge's receipt persistence, not a caller evidence field.
    from server.listener import _persist_relisten_context

    _persist_relisten_context(
        storage.resolve_path(link["metadata_file"]),
        {
            "contract": "germ.oida-relisten/v0.1",
            "remembered": True,
            "event_id": "synthetic-bridge-event",
            "akousma_id": later["akousma_id"],
            "output_sha256": link["output_sha256"],
        },
        [],
    )
    refs = [generated["akousma_id"], later["akousma_id"]]
    workflow = dict(
        contract="akouo/record-workflow/v0.1",
        request_id="decision:local-test",
        record_id="ak_decision_local",
        actor_ref="actor:test",
        created_at=(datetime.now(timezone.utc) + timedelta(seconds=2))
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z"),
        kind="decision",
        source_refs=refs,
        permissions=[
            dict(record_ref=r, status="granted", permission_ref="permission:owner") for r in refs
        ],
        supported_contracts=[
            "akouo/record-workflow/v0.1",
            "earworm/akousma/v1.7",
            "earworm/relations/v1",
            "earworm/generation-decision/v1",
        ],
        resolved_refs=["actor:test", "permission:owner", POLICY["id"]],
        output_ref=link["masa"]["representation_id"],
        decision=dict(
            contract="earworm/generation-decision/v1",
            decision_id="decision:local-test",
            actor_ref="actor:test",
            generation_ref=generated["akousma_id"],
            subsequent_listenings=[
                dict(
                    record_ref=later["akousma_id"],
                    listening_ref=later["auditum"]["listenings"][0]["listening_id"],
                )
            ],
            outcome="keep",
            reason="Synthetic fixture accepted by its declared decision actor.",
            policy_ref=POLICY["id"],
            policy_revision=POLICY["revision"],
            input_refs=refs,
            next_job={"status": "none", "reason": "Stop after this decision"},
            stop_outcome="stop",
            execution="not_requested",
        ),
    )
    return store, generated, later, dict(workflow=workflow, metadata_file=link["metadata_file"])


def test_retained_additive_decision_and_retry(decision_case):
    store, generated, later, body = decision_case
    result = retain(body)
    assert result["status"] == "retained"
    assert result["execution"] == "not_requested"
    assert result["quality_improvement"] == "not_established"
    assert store.get(generated["akousma_id"]) == generated
    assert store.get(later["akousma_id"]) == later
    assert retain(body)["reused"]
    changed = deepcopy(body)
    changed["workflow"]["decision"]["reason"] = "Different decision"
    with pytest.raises(ValueError, match="identity"):
        retain(changed)


@pytest.mark.parametrize(
    "case",
    [
        "hash",
        "missing",
        "listening",
        "policy",
        "execute",
        "generation",
        "receipt",
        "invented_evidence",
        "next_job",
    ],
)
def test_refuses_unbound_or_unsettled_decisions(decision_case, case):
    store, generated, later, body = decision_case
    d = body["workflow"]["decision"]
    if case == "hash":
        metadata = json.loads(storage.resolve_path(body["metadata_file"]).read_text())
        storage.resolve_path(metadata["output_audio_path"]).write_bytes(b"tampered")
    elif case == "missing":
        body["workflow"]["source_refs"][1] = "missing"
    elif case == "listening":
        d["subsequent_listenings"][0]["listening_ref"] = "invented-pass"
    elif case == "policy":
        d["policy_revision"] = "unknown"
    elif case == "execute":
        d["execution"] = "completed"
    elif case == "generation":
        d["generation_ref"] = "wrong"
    elif case == "receipt":
        metadata = json.loads(storage.resolve_path(body["metadata_file"]).read_text())
        storage.job_receipt_path(metadata["generation_job_id"]).unlink()
    elif case == "invented_evidence":
        body["output_evidence"] = {}
    else:
        d["next_job"] = {"status": "planned", "job_ref": "job:not-authorized"}
    with pytest.raises((ValueError, KeyError)):
        retain(body)
    assert store.get("ak_decision_local") is None


def test_route_and_planned_variation_do_not_submit_jobs(decision_case):
    store, generated, later, body = decision_case
    body["workflow"]["decision"].update(
        outcome="variation",
        next_job={"status": "planned", "job_ref": "job:later-owner-action"},
        stop_outcome="continue",
    )
    before = set(storage.jobs)
    response = TestClient(app).post("/akousma/generation/decision", json=body)
    assert response.status_code == 200, response.text
    assert set(storage.jobs) == before


@pytest.mark.parametrize(
    "decision_case", ["earlier", "restricted", "different_audio"], indirect=True
)
def test_later_account_must_be_current_permitted_and_bound(decision_case):
    store, _, _, body = decision_case
    with pytest.raises(ValueError):
        retain(body)
    assert store.get("ak_decision_local") is None


def test_record_audio_without_host_pass_binding_is_insufficient(decision_case):
    _, _, _, body = decision_case
    path = storage.resolve_path(body["metadata_file"])
    metadata = json.loads(path.read_text())
    metadata["extensions"].pop("germ.relisten")
    path.write_text(json.dumps(metadata))
    with pytest.raises(ValueError, match="host-retained"):
        retain(body)
